version: "3.9"

services:
  backend:
    build: ./backend
    container_name: spicky-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: spicky-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://backend:8080/dashboard/v1
    depends_on:
      - backend
